#ifndef HAVE_KEYBOARD_KEYS_H
#define HAVE_KEYBOARD_KEYS_H

enum keyboard_key_state {
	KEYBOARD_KEY_STATE_UP,
	KEYBOARD_KEY_STATE_DOWN,
};

enum keyboard_keys {
	// Start at 256 to not overlap with any actual char
	KEYBOARD_KEY_DUMMY = 255,
	KEYBOARD_KEY_ESCAPE,
	KEYBOARD_KEY_ENTER,
	KEYBOARD_KEY_ENTER_KP,
	KEYBOARD_KEY_DELETE,
	KEYBOARD_KEY_LCTRL,
	KEYBOARD_KEY_RCTRL,
	KEYBOARD_KEY_LSHIFT,
	KEYBOARD_KEY_RSHIFT,
	KEYBOARD_KEY_LALT,
	KEYBOARD_KEY_RALT,
	KEYBOARD_KEY_CAPS_LOCK,
	KEYBOARD_KEY_NUM_LOCK,
	KEYBOARD_KEY_SCROLL_LOCK,
	KEYBOARD_KEY_F1,
	KEYBOARD_KEY_F2,
	KEYBOARD_KEY_F3,
	KEYBOARD_KEY_F4,
	KEYBOARD_KEY_F5,
	KEYBOARD_KEY_F6,
	KEYBOARD_KEY_F7,
	KEYBOARD_KEY_F8,
	KEYBOARD_KEY_F9,
	KEYBOARD_KEY_F10,
	KEYBOARD_KEY_F11,
	KEYBOARD_KEY_F12,
	KEYBOARD_KEY_SYSRQ,
	KEYBOARD_KEY_HOME,
	KEYBOARD_KEY_END,
	KEYBOARD_KEY_PGUP,
	KEYBOARD_KEY_PGDOWN,
	KEYBOARD_KEY_INSERT,
	KEYBOARD_KEY_UP_ARROW,
	KEYBOARD_KEY_DOWN_ARROW,
	KEYBOARD_KEY_LEFT_ARROW,
	KEYBOARD_KEY_RIGHT_ARROW,
};

#endif // #ifndef HAVE_KEYBOARD_KEYS_H
